const Data = [
    {
        title:"Balanced Comfort Sacrifice",
        content:"The elephant in the room. Being in the comfort zone is perfectly healthy and should not cause or contribute to your anxiety and discomfort. 💖 It is important for us to recognise our need for a break and fulfilment. 🥰What is the comfort zone and how to identify it. The comfort zone is a psychological state of mind (in my life mostly present in relation with my career and hobbies) where things feel familiar, easy, and you are confident in yourself which bestows upon you the feeling of having control over your environment.The comfort zone stretches far beyond just career and hobbies, it can affect most of your everyday life such as dating, communication, relationships with people, but also the relationship with yourself. The most common hook of the comfort zone is that you are too fulfilled to notice your self growth, or better said, the lack of it. The only way you can identify and acknowledge whether you are in the comfort zone or not is if you are ready to accept the answer to that question."
    },
    {
        title:"Comfort Sacrifice",
        content:"The elephant in the room. Being in the comfort zone is perfectly healthy and should not cause or contribute to your anxiety and discomfort. 💖 It is important for us to recognise our need for a break and fulfilment. 🥰What is the comfort zone and how to identify it. The comfort zone is a psychological state of mind (in my life mostly present in relation with my career and hobbies) where things feel familiar, easy, and you are confident in yourself which bestows upon you the feeling of having control over your environment.The comfort zone stretches far beyond just career and hobbies, it can affect most of your everyday life such as dating, communication, relationships with people, but also the relationship with yourself. The most common hook of the comfort zone is that you are too fulfilled to notice your self growth, or better said, the lack of it. The only way you can identify and acknowledge whether you are in the comfort zone or not is if you are ready to accept the answer to that question."
    },
];

export default Data;